site_name: CUAHSI QA Documentation

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - About: index.md
  - Data Best Practices:
    - Sharing Samples and Sample Metadata: sample_data/registering_samples.md
    - Sharing Laboratory Analytical Data: sample_data/sample_data
    - Sharing Geospatial Data: geospatial_data/geospatial_data
    - Sharing Environmental Time Series Data: time_series_data/time_series_data
    - Sharing Multiple Data Types Together: multiple_data_types/multiple_data_types
